-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE*BS.SALES) TOTAL_SALES
FROM BOOK B, AUTHOR A,
    (SELECT BOOK_ID, SUM(SALES) SALES
    FROM BOOK_SALES
    WHERE TO_CHAR(SALES_DATE,'YYYYMM') = '202201'
    GROUP BY BOOK_ID) BS
WHERE B.BOOK_ID = BS.BOOK_ID
AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC