-- 코드를 입력하세요
SELECT CART_ID
  FROM (
    SELECT CART_ID
         , NAME
         , COUNT(1)
      FROM CART_PRODUCTS
     WHERE NAME IN ('Milk','Yogurt')
     GROUP BY CART_ID, NAME
      )
 GROUP BY CART_ID
HAVING COUNT(1) = 2
 ORDER BY CART_ID