-- 코드를 입력하세요
SELECT PRODUCT_CODE, PRICE*CNT AS SALES
FROM (
    SELECT A.PRODUCT_CODE, A.PRICE, SUM(SALES_AMOUNT) AS CNT
    FROM PRODUCT A, OFFLINE_SALE B
    WHERE A.PRODUCT_ID = B.PRODUCT_ID
    GROUP BY A.PRODUCT_CODE, A.PRICE
    )
ORDER BY SALES DESC, PRODUCT_CODE