-- 코드를 입력하세요
SELECT a.CAR_ID, a.CAR_TYPE, (a.DAILY_FEE * 30 * (1 - b.DISCOUNT_RATE * 0.01) ) AS FEE
  FROM  CAR_RENTAL_COMPANY_CAR a , CAR_RENTAL_COMPANY_DISCOUNT_PLAN  b
  where a.CAR_TYPE in ('세단','SUV') 
    AND b.DURATION_TYPE = '30일 이상'
    AND a.CAR_TYPE = b.CAR_TYPE
    AND (a.DAILY_FEE* 30* (1-b.DISCOUNT_RATE*0.01) ) BETWEEN 500000 AND 2000000
    and a.CAR_ID  NOT in
      (select CAR_ID        
         from CAR_RENTAL_COMPANY_RENTAL_HISTORY  
        where END_DATE >= TO_DATE('2022-11-01','YYYY-MM-DD')
      )
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC