-- 코드를 입력하세요
SELECT U.USER_ID
     , U.NICKNAME
     , U.CITY || ' ' || U.STREET_ADDRESS1 || ' ' || U.STREET_ADDRESS2 전체주소
     , REGEXP_REPLACE(U.TLNO, '(.{3})(.+)(.{4})', '\1-\2-\3') 전화번호
FROM USED_GOODS_USER U,
    (SELECT WRITER_ID, COUNT(*)
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*) >= 3) B
WHERE U.USER_ID = B.WRITER_ID
ORDER BY U.USER_ID DESC