-- 코드를 입력하세요
SELECT O.YEAR, O.MONTH, U.GENDER, COUNT(*) USERS
FROM USER_INFO U,
    (SELECT USER_ID, TO_CHAR(SALES_DATE,'YYYY') YEAR, TO_NUMBER(TO_CHAR(SALES_DATE,'MM')) MONTH
    FROM ONLINE_SALE
    GROUP BY USER_ID, TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'MM')) O
WHERE U.USER_ID = O.USER_ID
AND U.GENDER IS NOT NULL
GROUP BY O.YEAR, O.MONTH, U.GENDER
ORDER BY O.YEAR, O.MONTH, U.GENDER