-- 코드를 입력하세요
/*
SELECT YEAR
     , LTRIM(MONTH,'0') MONTH
     , COUNT(1) PUCHASED_USERS
     , ROUND(COUNT(1) / (SELECT COUNT(*)
                        FROM USER_INFO
                        WHERE TO_CHAR(JOINED, 'YYYY') = '2021'),1) AS PUCHASED_RATIO
FROM (
    SELECT TO_CHAR(SALES_DATE,'YYYY') YEAR
         , TO_CHAR(SALES_DATE,'MM') MONTH
         , USER_ID
    FROM ONLINE_SALE
    WHERE USER_ID IN (
        SELECT DISTINCT(USER_ID)
        FROM USER_INFO
        WHERE TO_CHAR(JOINED, 'YYYY') = '2021')
    GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'MM'), USER_ID)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH
*/

SELECT DISTINCT YEAR, MONTH, PUCHASED_USERS,
       ROUND(PUCHASED_USERS / (SELECT COUNT(*) FROM USER_INFO WHERE TO_CHAR(JOINED, 'YYYY')='2021'), 1) PUCHASED_RATIO
FROM (SELECT TO_NUMBER(TO_CHAR(S.SALES_DATE, 'YYYY')) YEAR,
           TO_NUMBER(TO_CHAR(S.SALES_DATE, 'FMMM')) MONTH,
           COUNT(DISTINCT I.USER_ID) OVER (PARTITION BY TO_CHAR(S.SALES_DATE, 'YYYY'), TO_CHAR(S.SALES_DATE, 'FMMM')) PUCHASED_USERS
    FROM ONLINE_SALE S
    JOIN USER_INFO I
    ON S.USER_ID = I.USER_ID
    WHERE TO_CHAR(I.JOINED, 'YYYY') = '2021')
ORDER BY YEAR, MONTH