-- 코드를 입력하세요
SELECT CAR_ID
     , CASE WHEN COUNT(*) = 2 THEN '대여중'
        ELSE '대여 가능' END AS AVAILABILITY
FROM (
SELECT *
FROM (
SELECT CAR_ID
     , CASE WHEN TO_CHAR(START_DATE,'YYYYMMDD') <= '20221016'
        AND TO_CHAR(END_DATE,'YYYYMMDD') >= '20221016' THEN '대여중'
        ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
GROUP BY CAR_ID, AVAILABILITY)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC