-- 코드를 입력하세요
SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE*O.AMOUNT TOTAL_SALES
FROM FOOD_PRODUCT P,
    (SELECT PRODUCT_ID, SUM(AMOUNT) AMOUNT
    FROM FOOD_ORDER 
     WHERE TO_CHAR(PRODUCE_DATE,'YYYYMM') = '202205'
    GROUP BY PRODUCT_ID) O
WHERE P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY P.PRICE*O.AMOUNT DESC, P.PRODUCT_ID ASC