-- 코드를 입력하세요
SELECT PP.CATEGORY, PP.MAX_PRICE, P.PRODUCT_NAME
FROM FOOD_PRODUCT P,
    (SELECT CATEGORY, MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY) PP
WHERE P.CATEGORY = PP.CATEGORY
AND P.PRICE = PP.MAX_PRICE
ORDER BY PP.MAX_PRICE DESC